[theme]
primaryColor = "#10a37f"  # ChatGPT's signature green
backgroundColor = "#1e1e1e"  # Deep gray background
secondaryBackgroundColor = "#2b2b2b"  # Slightly lighter for containers
textColor = "#ffffff"  # White text
font = "sans serif"
